services:
  -type: web
  name: invocie_project
  env: python
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn invoice_project.wsgi:application
  staticFiles:
    -baseDirectory: static
    servePath: /